version: "3"

services:
  honeypot:
    image: php:8.2-apache
    container_name: honeypot
    ports:
      - "8080:80" # Porta externa:interna
    volumes:
      - ./web:/var/www/html/
    restart: unless-stopped
