version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 32768:8080
    volumes:
      - /opt/srv:/data
      - /opt/config:/config
    environment:
      - FB_BASEURL=/
    restart: always
